### ISSUE TITLE
Don't start in ubuntu

### ISSUE THREAD

**Issue by g0ddest** [sgricci/dewdrop#23]
I just downloaded archive, install depends, run it and nothing happen. 
Ubuntu 15.04 python 2.7.9

**Comment by sgricci** [comment]
Hi @g0ddest,

Have you tried running it from the terminal and checking if there are any errors in the output?

Also, which desktop environment are you using? (Unity/Gnome-shell, etc.)

**Comment by g0ddest** [comment]
Unity, no errors, run from terminal.

29.09.2015 17:20, Steve Gricci пишет:

**Comment by sgricci** [comment]
Unity by default doesn't show all app icons in the "system tray". Because of this, the dewdrop icon may get blocked. The typical fix is to whitelist the application (though I haven't used Unity in quite some time, but I believe it still works).

More information here: http://www.howtogeek.com/68119/how-to-bring-app-icons-back-into-unitys-system-tray/

I'll see if I can test with the newest Ubuntu / Unity at some point and see if there is anything I can do to workaround this restriction, but editing the Unity configuration yourself is probably the best bet for now.

**Comment by g0ddest** [comment]
Here is no such option in dconf-editor. desktop > unity have only lenses and runner options. It has been replaced from 12.10. Bug still affects.

**Comment by sgricci** [comment]
Hrm. It looks like one of the dependencies isn't available anymore, so I can't even get it to run. Specifically pynotify (which is a libnotify binding for python).  I'll take a look soon and see what I can do to replace it, or just rewrite all this crap in something that's not in such a transitional phase as python.

**Comment by g0ddest** [comment]
Any changes?

**Comment by jrgifford** [comment]
Any updates?

**Comment by uiltondutra** [comment]
On Ubuntu 16.04 `sudo apt-get install python-appindicator` solves the issue.

**Comment by g0ddest** [comment]
@uiltondutra it works! thank you!
